# Generated by Django 4.2.16 on 2024-11-27 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.CharField(default='ID Cliente', max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('coordenadas', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('zona', models.CharField(choices=[('Otra', 'Otra'), ('NA', 'NA'), ('Usaquén', 'Usaquén'), ('Chapinero', 'Chapinero'), ('Santa Fe', 'Santa Fe'), ('San Cristóbal', 'San Cristóbal'), ('Usme', 'Usme'), ('Tunjuelito', 'Tunjuelito'), ('Bosa', 'Bosa'), ('Kennedy', 'Kennedy'), ('Fontibón', 'Fontibón'), ('Engativá', 'Engativá'), ('Suba', 'Suba'), ('Barrios Unidos', 'Barrios Unidos'), ('Teusaquillo', 'Teusaquillo'), ('Los Mártires', 'Los Mártires'), ('Antonio Nariño', 'Antonio Nariño'), ('Puente Aranda', 'Puente Aranda'), ('Candelaria', 'Candelaria'), ('Rafael Uribe Uribe', 'Rafael Uribe Uribe'), ('Ciudad Bolívar', 'Ciudad Bolívar'), ('Sumapaz', 'Sumapaz')], default='Otra', max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('item_empresa', models.CharField(default='ID Empresa', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nit', models.CharField(default='NIT Empresa', max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(default='Dirección empresa', max_length=255)),
                ('coord_emp', models.CharField(default='Formato: Latitud, Longitud', max_length=30)),
                ('telefono', models.CharField(default='+57 y Teléfono', max_length=15)),
                ('ciudad_emp', models.CharField(choices=[('BOGOTÁ D.C.', 'BOGOTÁ D.C.'), ('MANTA', 'MANTA'), ('TUNJA', 'TUNJA'), ('BELÉN', 'BELÉN'), ('MEDELLÍN', 'MEDELLÍN'), ('CALI', 'CALI'), ('BARRANQUILLA', 'BARRANQUILLA'), ('CARTAGENA', 'CARTAGENA'), ('BUCARAMANGA', 'BUCARAMANGA'), ('MANIZALES', 'MANIZALES'), ('PEREIRA', 'PEREIRA'), ('IBAGUÉ', 'IBAGUÉ'), ('SANTA MARTA', 'SANTA MARTA')], default='BOGOTÁ D.C.', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='portadas/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('item_producto', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('UM', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserSistem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('nro_pedido', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('item_pedido', models.IntegerField(default=1)),
                ('EstatusPed', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Confirmado', 'Confirmado'), ('Entregado', 'Entregado')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.cliente')),
                ('item_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.producto')),
            ],
            options={
                'unique_together': {('nro_pedido', 'item_pedido')},
            },
        ),
    ]
