# Generated by Django 5.1.5 on 2025-01-24 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_empresa', models.CharField(default='ID Empresa', max_length=10, unique=True)),
                ('nit', models.CharField(default='NIT Empresa', max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(default='Dirección empresa', max_length=255)),
                ('coord_emp', models.CharField(default='Formato: Latitud, Longitud', max_length=30)),
                ('telefono', models.CharField(default='+57 y Teléfono', max_length=15)),
                ('ciudad_emp', models.CharField(choices=[('BOGOTÁ D.C.', 'BOGOTÁ D.C.'), ('MANTA', 'MANTA'), ('TUNJA', 'TUNJA'), ('BELÉN', 'BELÉN'), ('MEDELLÍN', 'MEDELLÍN'), ('CALI', 'CALI'), ('BARRANQUILLA', 'BARRANQUILLA'), ('CARTAGENA', 'CARTAGENA'), ('BUCARAMANGA', 'BUCARAMANGA'), ('MANIZALES', 'MANIZALES'), ('PEREIRA', 'PEREIRA'), ('IBAGUÉ', 'IBAGUÉ'), ('SANTA MARTA', 'SANTA MARTA')], default='BOGOTÁ D.C.', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='portadas/')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSistem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('coordenadas', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('zona', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('item_empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_pedido', models.IntegerField(editable=False, unique=True)),
                ('EstatusPed', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Pagado', 'Pagado'), ('Entregado', 'Entregado')], max_length=20)),
                ('fecha_pedido', models.DateField(default=django.utils.timezone.now)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.cliente')),
                ('item_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.empresa')),
            ],
            options={
                'ordering': ['-nro_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('UM', models.CharField(default='UND', max_length=15)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_vencimiento', models.DateField()),
                ('item_producto', models.IntegerField(default=1, unique=True)),
                ('item_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.empresa', to_field='item_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.producto')),
            ],
        ),
    ]
