# Generated by Django 4.2.16 on 2024-11-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(default='Ciudad', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='coord_emp',
            field=models.CharField(default='Formato: Latitud, Longitud', max_length=30),
        ),
        migrations.AddField(
            model_name='empresa',
            name='item_empresa',
            field=models.CharField(default='ID Empresa', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='item_pedido',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nro_pedido',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='UM',
            field=models.CharField(default='UND', max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='item_producto',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(default='+57 y Teléfono', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together={('nro_pedido', 'item_pedido')},
        ),
    ]
