# Generated by Django 5.1.1 on 2025-01-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nro_pedido',
            field=models.IntegerField(unique=True),
        ),
    ]
