# Generated by Django 4.2.16 on 2024-11-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='item_pedido',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nro_pedido',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='UM',
            field=models.CharField(default='UND', max_length=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='item_producto',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together={('nro_pedido', 'item_pedido')},
        ),
    ]
