# Generated by Django 5.1.5 on 2025-01-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='EstatusPed',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Pagado', 'Pagado'), ('Entregado', 'Entregado'), ('Pagado', 'Pagado')], max_length=20),
        ),
    ]
