# Generated by Django 4.2.16 on 2024-11-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_item_pedido_pedido_nro_pedido_producto_um_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='item_empresa',
            field=models.CharField(default=1, max_length=10, unique=True),
        ),
    ]
