# Generated by Django 5.1.1 on 2025-01-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_nro_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nro_pedido',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
