# Generated by Django 4.2.16 on 2024-11-28 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_cliente_item_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(default='1000', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pedidos.empresa'),
        ),
    ]
