# Generated by Django 4.2.16 on 2024-11-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_cliente_item_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='ciudad',
            new_name='ciudad_emp',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nit',
            field=models.CharField(default='NIT Empresa', max_length=15, unique=True),
        ),
    ]
