# Generated by Django 4.2.16 on 2024-11-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_empresa_item_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='item_empresa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
