# Generated by Django 5.1.5 on 2025-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_nro_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='EstatusPed',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Pagado', 'Pagado'), ('Entregado', 'Entregado')], max_length=20),
        ),
    ]
