# Generated by Django 4.2.16 on 2024-11-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_rename_ciudad_empresa_ciudad_emp_empresa_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ciudad_emp',
            field=models.CharField(choices=[('BOGOTÁ D.C.', 'BOGOTÁ D.C.'), ('MANTA', 'MANTA'), ('TUNJA', 'TUNJA'), ('BELÉN', 'BELÉN'), ('MEDELLÍN', 'MEDELLÍN'), ('CALI', 'CALI'), ('BARRANQUILLA', 'BARRANQUILLA'), ('CARTAGENA', 'CARTAGENA'), ('BUCARAMANGA', 'BUCARAMANGA'), ('MANIZALES', 'MANIZALES'), ('PEREIRA', 'PEREIRA'), ('IBAGUÉ', 'IBAGUÉ'), ('SANTA MARTA', 'SANTA MARTA')], default='BOGOTÁ D.C.', max_length=30),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(default='Dirección empresa', max_length=255),
        ),
    ]
