# Generated by Django 4.2.16 on 2024-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_item_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='item_empresa',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
