# Generated by Django 4.2.16 on 2024-11-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_item_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='item_empresa',
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.empresa'),
        ),
    ]
