# Generated by Django 4.2.16 on 2024-11-05 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_remove_producto_item_empresa_producto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='item_empresa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedidos.empresa'),
        ),
    ]
